object_type: global_settings
overrides:
    "xmla.auth.token.enabled": "true"
    "xmla.discover.properties.daxdialect": "tabular1600"
    "connection.pool.user.idleConnectionDuration": "6 hours"
    "connection.pool.idleConnectionDuration": "6 hours"
   
    
